### PR TITLE
Update database credentials to match Trellis

### PR DESCRIPTION
**Pull request by mkaski**
The database credentials have changed: https://roots.io/trellis/docs/database-access/

### CODE REVIEW

**Comment by jillro** [comment]
The variable `mysql_root_password` is still available, and I think both solutions work correctly. For this reason, I don't see any point at introducing a unnecessary change, but I may be wrong. What are your rationals ?

**Comment by dylanlawrence** [comment]
I get this in the db log
```
Running '/etc/duply/example.com_database/pre' - FAILED (code 2)
Output: mysqldump: Got error: 1698: "Access denied for user 'root'@'localhost'"
```

**Comment by jillro** [comment]
Sorry, I cannot reproduce the bug. Can you check your actual root password and the one indicated in `mysql_root_password` match ? Did you change it since you ran `server.yml` ?

**Comment by dylanlawrence** [comment]
If I login to production:

```
mysql -u root -p
Enter password: 
ERROR 1698 (28000): Access denied for user 'root'@'localhost'
```

But if I sudo

```
sudo mysql -u root -p
Enter password: 
MariaDB [(none)]> 
```

So In `pre` I don't think `mysqldump` is running as root or sudo

_/etc/cron.d/backup_
```
0 0 * * * admin /usr/bin/duply /etc/duply/***.com_uploads purge_backup --force >> /var/log/duply/***.com_uploads.log 2>&1
0 0 * * * admin /usr/bin/duply /etc/duply/***.com_database purge_backup --force >> /var/log/duply/***.com_database.log 2>&1
```
_/etc/duply/***com_database/pre_
```
mysqldump -u root -p****** $DBNAME > ${WORKDIR}/dump
```

### UPDATE
The quick fix seems to be to change the root password to avoid _auth_socket_ plugin that says mysql user must by the system user.
```
UPDATE mysql.user SET authentication_string = PASSWORD('*****'), plugin = 'mysql_native_password' WHERE User ='root' AND Host = 'localhost';
FLUSH PRIVILEGES;
```
My apologies if this has nothing to do with this `role` @guilro,  but this is where I ended up.  
Maybe the mysql setup needs to be looked at in trellis?

**Comment by mkaski** [comment]
I believe changes to Stouts.backup are also necessary for this to work. https://github.com/mkaski/Stouts.backup/commit/887a76e7c8bfddfb7ad3b42d8de83121fe97d8f5

But there hasn't been much activity around PRs on Stouts.backup.

**Comment by jillro** [comment]
I check this tomorrow, in the meantime I don't make a new release :)

**Pull request merged**
